# Setup
title:               letboobu =world=
tagline:             'A Jekyll theme'
description:         'theme test'
url:                 'https://kwonbooyeon.github.io/'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Kwon Booyeon
  url:               
  email:             letboobu@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
