# Setup
title:               letbooby =world=
tagline:             'welcome to letboobuworld'
description:         'test'
url:                 http://kwonbooyeon.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Kwon Booyeon
  url:               http://kwonbooyeon.github.io
  email:             qndusrnjs@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
